sudo: required
dist: trusty
language: node_js
node_js:
  - "6.10"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  # - npm install -g @angular/cli

script:
  - ng build --prod --aot

after_success:
  - ./appendUserandDateToIndex.sh
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients: aerts.stefan@gmail.com
    on_failure: always
    on_success: always
